services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4173:4173
    # depends_on:
    #   db:
    #     condition: service_healthy
#   db:
#     image: mysql
#     restart: always
#     user: mysql
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/mysqlql/data
#     environment:
#       - MYSQL_DB=example
#       - MYSQL_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

